<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Ticket Report</title>

    <style>
        @page {
            size: A4 landscape;
            margin: 8mm;
        }

        html,
        body {
            margin: 0;
            padding: 0;
            width: 100%;
            min-height: 100%;
            font-family: Arial, sans-serif;
            color: #111827;
            font-size: 10px;
            background: #ffffff;
        }

        .page {
            width: 100%;
        }

        .print-actions {
            margin: 12px 0;
        }

        .print-btn {
            background: #b1e96f;
            border: none;
            padding: 9px 16px;
            border-radius: 8px;
            font-weight: bold;
            cursor: pointer;
        }

        .report-header {
            border-bottom: 3px solid #b1e96f;
            padding-bottom: 10px;
            margin-bottom: 12px;
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
        }

        .logo {
            height: 58px;
            max-width: 260px;
            object-fit: contain;
        }

        .report-title {
            font-size: 20px;
            font-weight: 800;
            margin-top: 6px;
        }

        .report-subtitle {
            color: #64748b;
            font-size: 11px;
            margin-top: 2px;
        }

        .meta {
            text-align: right;
            color: #475569;
            font-size: 10px;
            line-height: 1.5;
        }

        .filter-box {
            border: 1px solid #dbe3ed;
            background: #f8fafc;
            border-radius: 8px;
            padding: 9px 10px;
            margin-bottom: 12px;
        }

        .filter-title {
            font-weight: 800;
            margin-bottom: 6px;
            color: #111827;
            font-size: 11px;
        }

        .filter-row {
            display: flex;
            flex-wrap: wrap;
            gap: 6px;
        }

        .filter-chip {
            border: 1px solid #d1d5db;
            background: #ffffff;
            border-radius: 999px;
            padding: 5px 9px;
            font-size: 10px;
            white-space: nowrap;
        }

        .filter-chip strong {
            color: #111827;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            table-layout: fixed;
            page-break-inside: auto;
        }

        thead {
            display: table-header-group;
        }

        tr {
            page-break-inside: avoid;
            page-break-after: auto;
        }

        th {
            background: #111827;
            color: #ffffff;
            text-align: left;
            padding: 7px 5px;
            border: 1px solid #111827;
            font-size: 9px;
            font-weight: 800;
        }

        td {
            padding: 6px 5px;
            border: 1px solid #d1d5db;
            vertical-align: top;
            font-size: 8.8px;
            word-wrap: break-word;
        }

        tbody tr:nth-child(even) {
            background: #f8fafc;
        }

        .footer-note {
            margin-top: 12px;
            color: #64748b;
            font-size: 9px;
            text-align: center;
        }

        .ticket-no {
            width: 12%;
        }

        .org {
            width: 15%;
        }

        .user {
            width: 12%;
        }

        .subject {
            width: 25%;
        }

        .priority {
            width: 8%;
        }

        .status {
            width: 10%;
        }

        .created {
            width: 11%;
        }

        .closed-by {
            width: 7%;
        }

        @media print {
            .print-actions {
                display: none;
            }

            body {
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }
        }
    </style>
</head>

<body>

    <div class="page">

        <div class="print-actions">
            <button onclick="window.print()" class="print-btn">
                Print / Save PDF
            </button>
        </div>

        <div class="report-header">

            <div>
                <img
                    src="<?= BASE_URL ?>/assets/images/samtech-logo.png"
                    class="logo"
                    alt="Samtech">

                <div class="report-title">
                    Ticket Report
                </div>

                <div class="report-subtitle">
                    Samtech Helpdesk Management System
                </div>
            </div>

            <div class="meta">
                <strong>Generated On</strong><br>
                <?= date('d M Y, h:i A'); ?><br><br>
                <strong>Generated By</strong><br>
                <?= htmlspecialchars($_SESSION['auth_user_name'] ?? 'System'); ?>
            </div>

        </div>

        <div class="filter-box">
            <div class="filter-title">
                Applied Filters
            </div>

            <div class="filter-row">
                <?php if (empty($appliedFilters)): ?>

                    <span class="filter-chip">
                        <strong>All Tickets</strong>
                    </span>

                <?php else: ?>

                    <?php foreach ($appliedFilters as $label => $value): ?>

                        <span class="filter-chip">
                            <strong><?= htmlspecialchars($label); ?>:</strong>
                            <?= htmlspecialchars($value); ?>
                        </span>

                    <?php endforeach; ?>

                <?php endif; ?>
            </div>
        </div>

        <table>
            <thead>
                <tr>
                    <th class="ticket-no">Ticket No</th>
                    <th class="org">Organization</th>
                    <th class="user">User</th>
                    <th class="subject">Subject</th>
                    <th class="priority">Priority</th>
                    <th class="status">Status</th>
                    <th class="created">Created</th>
                    <th class="closed-by">Closed By</th>
                </tr>
            </thead>

            <tbody>

                <?php if (empty($tickets)): ?>

                    <tr>
                        <td colspan="8" style="text-align:center;">
                            No records found.
                        </td>
                    </tr>

                <?php else: ?>

                    <?php foreach ($tickets as $ticket): ?>

                        <tr>
                            <td><?= htmlspecialchars($ticket['ticket_no']); ?></td>
                            <td><?= htmlspecialchars($ticket['organization_name'] ?? '-'); ?></td>
                            <td><?= htmlspecialchars($ticket['customer_name'] ?? '-'); ?></td>
                            <td><?= htmlspecialchars($ticket['subject']); ?></td>
                            <td><?= htmlspecialchars(ucfirst($ticket['priority'])); ?></td>
                            <td><?= htmlspecialchars(ucwords(str_replace('_', ' ', $ticket['status']))); ?></td>
                            <td><?= htmlspecialchars($ticket['created_at']); ?></td>
                            <td><?= htmlspecialchars($ticket['closed_by_agent_name'] ?? '-'); ?></td>
                        </tr>

                    <?php endforeach; ?>

                <?php endif; ?>

            </tbody>
        </table>

        <div class="footer-note">
            This report is system generated by Samtech Helpdesk.
        </div>

    </div>

    <script>
        window.onload = function() {
            setTimeout(function() {
                window.print();
            }, 500);
        };
    </script>

</body>

</html>