<!DOCTYPE html>
<html>

<head>

    <meta charset="UTF-8">

    <title>Ticket Detail Report</title>

    <style>
        @page {
            size: Letter portrait;
            margin: 10mm;
        }

        body {
            margin: 0;
            font-family: Arial, sans-serif;
            color: #111827;
            font-size: 11px;
        }

        .print-btn {
            background: #b1e96f;
            border: none;
            padding: 10px 18px;
            border-radius: 8px;
            font-weight: bold;
            cursor: pointer;
            margin-bottom: 20px;
        }

        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 3px solid #b1e96f;
            padding-bottom: 15px;
            margin-bottom: 20px;
        }

        .logo {
            width: 190px;
        }

        .title {
            font-size: 26px;
            font-weight: bold;
        }

        .subtitle {
            color: #64748b;
            margin-top: 4px;
        }

        .meta {
            text-align: right;
            font-size: 11px;
            color: #64748b;
        }

        .section {
            margin-bottom: 22px;
        }

        .section-title {
            font-size: 15px;
            font-weight: bold;
            margin-bottom: 12px;
            border-left: 5px solid #b1e96f;
            padding-left: 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th {
            width: 28%;
            background: #f8fafc;
            text-align: left;
            padding: 10px;
            border: 1px solid #d1d5db;
        }

        td {
            padding: 10px;
            border: 1px solid #d1d5db;
        }

        .description {
            border: 1px solid #d1d5db;
            background: #fafafa;
            padding: 15px;
            line-height: 1.7;
        }

        .reply {
            border: 1px solid #dbe3ed;
            border-radius: 10px;
            margin-bottom: 18px;
        }

        .reply-header {
            background: #f8fafc;
            padding: 10px 14px;
            border-bottom: 1px solid #e5e7eb;
            display: flex;
            justify-content: space-between;
        }

        .reply-body {
            padding: 14px;
        }

        .timeline {
            border-left: 3px solid #b1e96f;
            padding-left: 16px;
            margin-bottom: 18px;
        }

        .footer {
            margin-top: 30px;
            text-align: center;
            color: #64748b;
            font-size: 10px;
        }

        @media print {

            .print-btn {
                display: none;
            }

            body {
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }

        }
    </style>

</head>

<body>

    <button onclick="window.print()" class="print-btn">
        Print / Save PDF
    </button>

    <div class="header">

        <div>

            <img
                src="<?= BASE_URL ?>/assets/images/samtech-logo-report.png"
                class="logo">

            <div class="title">
                Ticket Detail Report
            </div>

            <div class="subtitle">
                Samtech Helpdesk Management System
            </div>

        </div>

        <div class="meta">

            <strong>Generated On</strong><br>

            <?= date('d M Y h:i A'); ?>

            <br><br>

            <strong>Generated By</strong><br>

            <?= htmlspecialchars($_SESSION['auth_user_name']); ?>

        </div>

    </div>

    <div class="section">

        <div class="section-title">
            Ticket Information
        </div>

        <table>

            <tr>
                <th>Ticket Number</th>
                <td><?= htmlspecialchars($ticket['ticket_no']); ?></td>
            </tr>

            <tr>
                <th>Organization</th>
                <td><?= htmlspecialchars($ticket['organization_name']); ?></td>
            </tr>

            <tr>
                <th>User</th>
                <td><?= htmlspecialchars($ticket['customer_name']); ?></td>
            </tr>

            <tr>
                <th>Email</th>
                <td><?= htmlspecialchars($ticket['customer_email']); ?></td>
            </tr>

            <tr>
                <th>Subject</th>
                <td><?= htmlspecialchars($ticket['subject']); ?></td>
            </tr>

            <tr>
                <th>Status</th>
                <td><?= htmlspecialchars(ucwords(str_replace('_', ' ', $ticket['status']))); ?></td>
            </tr>

            <tr>
                <th>Priority</th>
                <td><?= htmlspecialchars(ucfirst($ticket['priority'])); ?></td>
            </tr>

            <tr>
                <th>Created</th>
                <td><?= htmlspecialchars($ticket['created_at']); ?></td>
            </tr>

            <tr>
                <th>Closed</th>
                <td><?= $ticket['closed_at'] ?: '-'; ?></td>
            </tr>

            <tr>
                <th>Closed By</th>
                <td><?= htmlspecialchars($ticket['closed_by_agent_name'] ?? '-'); ?></td>
            </tr>

        </table>

    </div>

    <div class="section">

        <div class="section-title">
            Description
        </div>

        <div class="description">

            <?= nl2br(htmlspecialchars($ticket['description'])); ?>

        </div>

    </div>

    <?php if (!empty($attachments)): ?>

        <div class="section">

            <div class="section-title">
                Ticket Attachments
            </div>

            <ul>

                <?php foreach ($attachments as $attachment): ?>

                    <li>

                        <?= htmlspecialchars($attachment['original_name']); ?>

                    </li>

                <?php endforeach; ?>

            </ul>

        </div>

    <?php endif; ?>

    <div class="section">

        <div class="section-title">
            Conversation History
        </div>

        <?php if (empty($replies)): ?>

            No Replies Available

        <?php else: ?>

            <?php foreach ($replies as $reply): ?>

                <div class="reply">

                    <div class="reply-header">

                        <strong>

                            <?= htmlspecialchars($reply['full_name']); ?>

                            (<?= ucfirst($reply['role']); ?>)

                        </strong>

                        <span>

                            <?= htmlspecialchars($reply['created_at']); ?>

                        </span>

                    </div>

                    <div class="reply-body">

                        <?= nl2br(htmlspecialchars($reply['message'])); ?>

                        <?php if (!empty($replyAttachments[$reply['id']])): ?>

                            <hr>

                            <strong>Attachments</strong>

                            <ul>

                                <?php foreach ($replyAttachments[$reply['id']] as $file): ?>

                                    <li>

                                        <?= htmlspecialchars($file['original_name']); ?>

                                    </li>

                                <?php endforeach; ?>

                            </ul>

                        <?php endif; ?>

                    </div>

                </div>

            <?php endforeach; ?>

        <?php endif; ?>

    </div>

    <div class="section">

        <div class="section-title">
            Status Timeline
        </div>

        <?php if (empty($statusHistory)): ?>

            No Status History

        <?php else: ?>

            <?php foreach ($statusHistory as $history): ?>

                <div class="timeline">

                    <strong>

                        <?= ucwords(str_replace('_', ' ', $history['old_status'])); ?>

                        →

                        <?= ucwords(str_replace('_', ' ', $history['new_status'])); ?>

                    </strong>

                    <br>

                    <?= htmlspecialchars($history['full_name']); ?>

                    <br>

                    <?= htmlspecialchars($history['created_at']); ?>

                </div>

            <?php endforeach; ?>

        <?php endif; ?>

    </div>

    <div class="footer">

        This report was automatically generated by Samtech Helpdesk.

    </div>

    <script>
        window.onload = function() {

            window.print();

        }
    </script>

</body>

</html>