<!DOCTYPE html>
<html>

<head>

<meta charset="UTF-8">

<title>Ticket Report</title>

<style>

@page{
    size:A4 landscape;
    margin:12mm;
}

body{
    font-family:Arial,sans-serif;
    color:#111827;
    font-size:11px;
    margin:0;
}

.header{
    width:100%;
    border-bottom:3px solid #b1e96f;
    padding-bottom:15px;
    margin-bottom:20px;
}

.logo{
    height:55px;
}

.title{
    font-size:24px;
    font-weight:bold;
    margin-top:10px;
}

.subtitle{
    color:#6b7280;
    font-size:13px;
}

.generated{
    float:right;
    text-align:right;
    margin-top:-70px;
    font-size:11px;
    color:#6b7280;
}

table{
    width:100%;
    border-collapse:collapse;
}

th{
    background:#111827;
    color:white;
    padding:10px;
    border:1px solid #d1d5db;
    font-size:11px;
}

td{
    padding:8px;
    border:1px solid #e5e7eb;
    font-size:10px;
    vertical-align:top;
}

.footer{
    margin-top:20px;
    text-align:center;
    color:#6b7280;
    font-size:10px;
}

.print-btn{
    margin-bottom:20px;
}

@media print{

.print-btn{
display:none;
}

body{
margin:0;
}

}

</style>

</head>

<body>

<div class="print-btn">

<button onclick="window.print();">

Print Report

</button>

</div>

<div class="header">

<img
src="<?= BASE_URL ?>/assets/images/samtech-logo.png"
class="logo">

<div class="title">

Ticket Report

</div>

<div class="subtitle">

Samtech Helpdesk Management System

</div>

<div class="generated">

Generated :
<br>

<?= date('d M Y h:i A'); ?>

</div>

</div>

<table>

<thead>

<tr>

<th>Ticket No</th>

<th>Organization</th>

<th>User</th>

<th>Subject</th>

<th>Priority</th>

<th>Status</th>

<th>Created</th>

<th>Closed By</th>

</tr>

</thead>

<tbody>

<?php if(empty($tickets)): ?>

<tr>

<td colspan="8" style="text-align:center">

No Records Found

</td>

</tr>

<?php else: ?>

<?php foreach($tickets as $ticket): ?>

<tr>

<td><?= htmlspecialchars($ticket['ticket_no']) ?></td>

<td><?= htmlspecialchars($ticket['organization_name'] ?? '-') ?></td>

<td><?= htmlspecialchars($ticket['customer_name'] ?? '-') ?></td>

<td><?= htmlspecialchars($ticket['subject']) ?></td>

<td><?= ucfirst($ticket['priority']) ?></td>

<td><?= ucwords(str_replace('_',' ',$ticket['status'])) ?></td>

<td><?= htmlspecialchars($ticket['created_at']) ?></td>

<td><?= htmlspecialchars($ticket['closed_by_agent_name'] ?? '-') ?></td>

</tr>

<?php endforeach; ?>

<?php endif; ?>

</tbody>

</table>

<div class="footer">

This report is system generated by Samtech Helpdesk.

</div>

<script>

window.onload=function(){

setTimeout(function(){

window.print();

},400);

}

</script>

</body>

</html>