<?php
$logoPath = ROOT_PATH . '/public/assets/images/samtech-logo-report.png';
$logoSrc = file_exists($logoPath)
    ? 'data:image/png;base64,' . base64_encode(file_get_contents($logoPath))
    : BASE_URL . '/assets/images/samtech-logo-report.png';
?>
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Ticket Report</title>

    <style>
        @page {
            size: A4 landscape;
            margin: 8mm;
        }

        html, body {
            margin: 0;
            padding: 0;
            width: 100%;
            font-family: Arial, Helvetica, sans-serif;
            color: #111827;
            background: #ffffff;
            font-size: 10px;
        }

        .page {
            width: 100%;
        }

        .print-actions {
            margin: 12px 0;
        }

        .print-btn {
            background: #b1e96f;
            border: none;
            padding: 9px 16px;
            border-radius: 8px;
            font-weight: bold;
            cursor: pointer;
        }

        .header-table {
            width: 100%;
            border-bottom: 3px solid #b1e96f;
            padding-bottom: 10px;
            margin-bottom: 12px;
            border-collapse: collapse;
        }

        .logo {
            width: 180px;
            height: auto;
        }

        .report-title {
            font-size: 20px;
            font-weight: 800;
            margin-top: 6px;
            color: #111827;
        }

        .report-subtitle {
            color: #64748b;
            font-size: 10px;
            margin-top: 2px;
        }

        .meta {
            text-align: right;
            color: #475569;
            font-size: 9.5px;
            line-height: 1.5;
        }

        .criteria {
            margin: 0 0 12px 0;
            padding-bottom: 8px;
            border-bottom: 1px solid #e5e7eb;
            color: #374151;
            font-size: 10px;
            line-height: 1.6;
        }

        .criteria-label {
            font-weight: 800;
            color: #111827;
        }

        table.data-table {
            width: 100%;
            border-collapse: collapse;
            table-layout: fixed;
        }

        table.data-table th {
            background: #111827;
            color: #ffffff;
            text-align: left;
            padding: 7px 6px;
            border: 1px solid #111827;
            font-size: 9.5px;
            font-weight: 800;
        }

        table.data-table td {
            padding: 6px;
            border: 1px solid #d1d5db;
            vertical-align: top;
            font-size: 9px;
            word-wrap: break-word;
        }

        table.data-table tbody tr:nth-child(even) {
            background: #f8fafc;
        }

        .footer-note {
            margin-top: 12px;
            padding-top: 6px;
            border-top: 1px solid #e5e7eb;
            color: #64748b;
            font-size: 8.5px;
            text-align: center;
        }

        .ticket-no { width: 13%; }
        .org { width: 13%; }
        .user { width: 11%; }
        .subject { width: 28%; }
        .priority { width: 7%; }
        .status { width: 10%; }
        .created { width: 10%; }
        .closed-by { width: 8%; }

        @media print {
            .print-actions {
                display: none !important;
            }

            body {
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }
        }
    </style>
</head>

<body>

<div class="page">

    <?php if (empty($isPdfDownload)): ?>
    <div class="print-actions">
        <button onclick="window.print()" class="print-btn">
            Print / Save PDF
        </button>
    </div>
    <?php endif; ?>

    <table class="header-table">
        <tr>
            <td style="border:none; vertical-align:top; text-align:left; padding:0;">
                <img src="<?= $logoSrc; ?>" class="logo" alt="Samtech">
                <div class="report-title">Ticket Report</div>
                <div class="report-subtitle">Samtech Helpdesk Management System</div>
            </td>
            <td style="border:none; vertical-align:top; text-align:right; padding:0;" class="meta">
                <strong>Generated On:</strong> <?= date('d M Y, h:i A'); ?><br>
                <strong>Generated By:</strong> <?= htmlspecialchars($_SESSION['auth_user_name'] ?? 'System'); ?><br>
                <strong>Total Records:</strong> <?= count($tickets); ?>
            </td>
        </tr>
    </table>

    <?php
        $criteria = [];

        if (!empty($filters['organization_id']) && !empty($organizations)) {
            foreach ($organizations as $o) {
                if ($o['id'] == $filters['organization_id']) {
                    $criteria[] = '<span class="criteria-label">Organization:</span> ' . htmlspecialchars($o['name']);
                    break;
                }
            }
        }

        if (!empty($filters['user_id']) && !empty($users)) {
            foreach ($users as $u) {
                if ($u['id'] == $filters['user_id']) {
                    $criteria[] = '<span class="criteria-label">User:</span> ' . htmlspecialchars($u['full_name']);
                    break;
                }
            }
        }

        if (!empty($filters['agent_id']) && !empty($agents)) {
            foreach ($agents as $a) {
                if ($a['id'] == $filters['agent_id']) {
                    $criteria[] = '<span class="criteria-label">Agent:</span> ' . htmlspecialchars($a['full_name']);
                    break;
                }
            }
        }

        if (!empty($filters['status'])) {
            $criteria[] = '<span class="criteria-label">Status:</span> ' . htmlspecialchars(ucwords(str_replace('_', ' ', $filters['status'])));
        }

        if (!empty($filters['priority'])) {
            $criteria[] = '<span class="criteria-label">Priority:</span> ' . htmlspecialchars(ucfirst($filters['priority']));
        }

        if (!empty($filters['date_from'])) {
            $criteria[] = '<span class="criteria-label">From:</span> ' . htmlspecialchars($filters['date_from']);
        }

        if (!empty($filters['date_to'])) {
            $criteria[] = '<span class="criteria-label">To:</span> ' . htmlspecialchars($filters['date_to']);
        }
    ?>

    <?php if (!empty($criteria)): ?>
        <div class="criteria">
            <?= implode(' &nbsp;|&nbsp; ', $criteria); ?>
        </div>
    <?php endif; ?>

    <table class="data-table">
        <thead>
            <tr>
                <th class="ticket-no">Ticket No</th>
                <th class="org">Organization</th>
                <th class="user">User</th>
                <th class="subject">Subject</th>
                <th class="priority">Priority</th>
                <th class="status">Status</th>
                <th class="created">Created</th>
                <th class="closed-by">Closed By</th>
            </tr>
        </thead>
        <tbody>

        <?php if (empty($tickets)): ?>
            <tr>
                <td colspan="8" style="text-align: center; padding: 18px; color: #64748b;">
                    No tickets found matching the selected report criteria.
                </td>
            </tr>
        <?php else: ?>

            <?php foreach ($tickets as $ticket): ?>
                <tr>
                    <td class="ticket-no"><strong><?= htmlspecialchars($ticket['ticket_no'] ?? '-'); ?></strong></td>
                    <td class="org"><?= htmlspecialchars($ticket['organization_name'] ?? '-'); ?></td>
                    <td class="user"><?= htmlspecialchars($ticket['customer_name'] ?? '-'); ?></td>
                    <td class="subject"><?= htmlspecialchars($ticket['subject'] ?? '-'); ?></td>
                    <td class="priority"><?= htmlspecialchars(ucfirst($ticket['priority'] ?? '')); ?></td>
                    <td class="status"><?= htmlspecialchars(ucwords(str_replace('_', ' ', $ticket['status'] ?? ''))); ?></td>
                    <td class="created"><?= !empty($ticket['created_at']) ? date('Y-m-d H:i', strtotime($ticket['created_at'])) : '-'; ?></td>
                    <td class="closed-by"><?= htmlspecialchars($ticket['closed_by_agent_name'] ?? '-'); ?></td>
                </tr>
            <?php endforeach; ?>

        <?php endif; ?>

        </tbody>
    </table>

    <div class="footer-note">
        Samtech Helpdesk • System Generated Report
    </div>

</div>

<?php if (empty($isPdfDownload)): ?>
<script>
    window.addEventListener("load", function () {
        window.print();
    });
</script>
<?php endif; ?>

</body>
</html>